---
name: Clothes
version: 4.0.0
main: TungstenVn\Clothes\Clothes
api:
- 4.0.0
author: TungstenVn
commands:
  clo:
    description: Open clothes menu
  clothes:
    description: Open clothes menu
  cos:
    description: Open cosplay menu
  cosplays:
    description: Open cosplay menu

...
