---
#set to true if you wanna delete the player's skin in saveskin dir when the player left the server
DeleteSkinAfterQuitting: true

#get update for new release
enableUpdateChecker: false

#type as the following to add a perm to a cloth or cosplay
perms:
  pika blue: pika.perm
  sitdown: sitdown.perm

  long_neck: tungdeptrai.perm